version: '3.8'

x-common-api-settings: &common-settings
  image: link-shortener-devops
  volumes:
    - ./data/:/app/data/
  environment:
    - LINKS_PATH=./data/links.json  

services:
  api-node-1:
    <<: *common-settings
    ports:
      - "7001:8080"

  api-node-2:
    <<: *common-settings
    ports:
      - "7002:8080"

  echo-node:
    image: link-shortener-devops
    depends_on:
      - api-node-1
    volumes:
      - ./data/:/app/data/
    environment:
      - LINKS_PATH=./data/links.json
    command: ["echo", "API container is up!"]