version: '3.8'

x-common-api-settings: &common-settings
  # image: link-shortener-devops
  build: 
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./data/:/app/data/
  environment:
    - LINKS_PATH=./data/links.json
  healthcheck:
      test: ["CMD", "curl", "localhost:8080/api/health_check"]
      interval: 30s
      timeout: 3s
      retries: 10 
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 100m
      reservations: 
        cpus: '0.5'
        memory: 10m

services:
  api-node-1:
    <<: *common-settings
    ports:
      - "7001:8080"

  api-node-2:
    <<: *common-settings
    ports:
      - "7002:8080"

  echo-node:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api-node-1
      - api-node-2
    volumes:
      - ./data/:/app/data/
    environment:
      - LINKS_PATH=./data/links.json
    command: ["echo", "API container is up!"]