version: '3.8'

x-common-api-settings: &common-settings
  build: 
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./data/:/app/data/
    - ./:/app/
  environment:
    - LINKS_PATH=./data/links.json
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  networks:
    - elk
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 100m
      reservations: 
        cpus: '0.5'
        memory: 10m

services:
  api-node-1:
    <<: *common-settings
    ports:
      - "8080:8080"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api-node-1


  # delete_invalid_links:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./data/:/app/data/
  #   environment:
  #     - LINKS_PATH=./data/links.json
  #   command: ["python", "delete_invalid_links.py"]

  elastic:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elastic_data/:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elastic
    networks:
      - elk
  
networks:

  elk:
    driver: bridge